name: Render & Deploy Headless Page

on:
  push:
    branches: [main]

jobs:
  render_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Render page with Puppeteer
        run: npm run render
        env:
          TARGET_URL: 'https://docs.nightwatch.io'  # Or use a GitHub secret here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist